export const yugiohRaces: { value: string; viewValue: string }[] = [
  { value: 'Aqua', viewValue: 'Aqua' },
  { value: 'Beast', viewValue: 'Beast' },
  { value: 'Beast-Warrior', viewValue: 'Beast-Warrior' },
  { value: 'Creator-God', viewValue: 'Creator-God' },
  { value: 'Cyberse', viewValue: 'Cyberse' },
  { value: 'Dinosaur', viewValue: 'Dinosaur' },
  { value: 'Divine-Beast', viewValue: 'Divine-Beast' },
  { value: 'Dragon', viewValue: 'Dragon' },
  { value: 'Fairy', viewValue: 'Fairy' },
  { value: 'Fiend', viewValue: 'Fiend' },
  { value: 'Fish', viewValue: 'Fish' },
  { value: 'Insect', viewValue: 'Insect' },
  { value: 'Machine', viewValue: 'Machine' },
  { value: 'Plant', viewValue: 'Plant' },
  { value: 'Psychic', viewValue: 'Psychic' },
  { value: 'Pyro', viewValue: 'Pyro' },
  { value: 'Reptile', viewValue: 'Reptile' },
  { value: 'Rock', viewValue: 'Rock' },
  { value: 'Sea Serpent', viewValue: 'Sea Serpent' },
  { value: 'Spellcaster', viewValue: 'Spellcaster' },
  { value: 'Thunder', viewValue: 'Thunder' },
  { value: 'Warrior', viewValue: 'Warrior' },
  { value: 'Winged Beast', viewValue: 'Winged Beast' },
  { value: 'Wyrm', viewValue: 'Wyrm' },
  { value: 'Zombie', viewValue: 'Zombie' },
];

export const yugiohCardTypes: { value: string; viewValue: string }[] = [
  { value: 'normal', viewValue: 'Normal' },
  { value: 'effect', viewValue: 'Effect' },
  { value: 'ritual', viewValue: 'Ritual' },
  { value: 'fusion', viewValue: 'Fusion' },
  { value: 'synchro', viewValue: 'Synchro' },
  { value: 'xyz', viewValue: 'Xyz' },
  { value: 'link', viewValue: 'Link' },
  { value: 'normal_pendulum', viewValue: 'Normal Pendulum' },
  { value: 'effect_pendulum', viewValue: 'Effect Pendulum' },
  { value: 'ritual_pendulum', viewValue: 'Ritual Pendulum' },
  { value: 'fusion_pendulum', viewValue: 'Fusion Pendulum' },
  { value: 'synchro_pendulum', viewValue: 'Synchro Pendulum' },
  { value: 'xyz_pendulum', viewValue: 'Xyz Pendulum' },
  { value: 'spell', viewValue: 'Spell' },
  { value: 'trap', viewValue: 'Trap' },
  { value: 'token', viewValue: 'Token' },
  { value: 'skill', viewValue: 'Skill' },
];
